---
- name: reload systctl file
  shell: "sysctl -p"

- name: set setenforce zero
  shell: "setenforce 0"

- name: add ntp crontab 
  cron: name="per 5 min run ntpdate" minute=*/5 job="ntpdate {{ ntpserver }} >/dev/null 2>&1"






